// src/mockData.js
const mockData = [
    {
      productItems: "Shirt",
      itemsNo: "HK4886",
      incoming: 14,
      category: "Molasses",
      date: "12 Feb 2024",
      quantity: 240,
      price: "$8,542.82",
      paid: true,
      action: "View Shipments",
    },
    {
      productItems: "Notebook",
      itemsNo: "HK4887",
      incoming: 12,
      category: "Stationery",
      date: "13 Feb 2024",
      quantity: 140,
      price: "$3,742.82",
      paid: true,
      action: "View Shipments",
    },
    {
      productItems: "Laptop",
      itemsNo: "HK4888",
      incoming: 16,
      category: "Electronics",
      date: "14 Feb 2024",
      quantity: 340,
      price: "$54,542.82",
      paid: false,
      action: "Cancelled",
    },
    {
      productItems: "Carrots",
      itemsNo: "HK4889",
      incoming: 10,
      category: "Vegetables",
      date: "15 Feb 2024",
      quantity: 24,
      price: "$542.82",
      paid: true,
      action: "Ship Order",
    },
    {
      productItems: "Oatmeal",
      itemsNo: "HK4890",
      incoming: 19,
      category: "Groceries",
      date: "16 Feb 2024",
      quantity: 140,
      price: "$1,542.82",
      paid: true,
      action: "View Shipments",
    },
    {
      productItems: "Honey",
      itemsNo: "HK4891",
      incoming: 18,
      category: "Groceries",
      date: "17 Feb 2024",
      quantity: 240,
      price: "$8,542.82",
      paid: true,
      action: "Ship Order",
    },
    {
      productItems: "Molasses",
      itemsNo: "HK4892",
      incoming: 12,
      category: "Groceries",
      date: "18 Feb 2024",
      quantity: 340,
      price: "$8,542.82",
      paid: false,
      action: "Pending",
    },
  ];
  
  export default mockData;
  